/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tfR2AZK8c5a
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export function Component() {
  return (
    (<div className="flex flex-col min-h-screen bg-background">
      <header
        className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link href="#" className="text-2xl font-bold" prefetch={false}>
            Hospital Management
          </Link>
          <nav className="hidden md:flex gap-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              OPD Queuing
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Bed Availability
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Patient Admission
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              City-wide Integration
            </Link>
          </nav>
        </div>
        <Button variant="outline" className="hidden md:inline-flex">
          Contact Us
        </Button>
      </header>
      <main className="flex-1 py-12">
        <section
          id="opd"
          className="container mx-auto px-4 md:px-6 grid md:grid-cols-2 gap-8">
          <div>
            <h2 className="text-3xl font-bold mb-4">OPD Queuing</h2>
            <p className="text-muted-foreground mb-6">
              Manage and optimize patient queues in different OPD departments.
            </p>
            <div className="grid gap-4">
              <Card>
                <CardHeader>
                  <CardTitle>Real-time Queue Monitoring</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Get live updates on patient queue status and estimated wait times for each OPD department.</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Appointment Scheduling</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Allow patients to easily schedule appointments and manage their healthcare visits.</p>
                </CardContent>
              </Card>
            </div>
          </div>
          <div>
            <img
              src="/placeholder.svg"
              alt="OPD Queuing"
              width={600}
              height={400}
              className="rounded-lg object-cover"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
          </div>
        </section>
        <section
          id="beds"
          className="container mx-auto px-4 md:px-6 grid md:grid-cols-2 gap-8 mt-12">
          <div>
            <img
              src="/placeholder.svg"
              alt="Bed Availability"
              width={600}
              height={400}
              className="rounded-lg object-cover"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
          </div>
          <div>
            <h2 className="text-3xl font-bold mb-4">Bed Availability</h2>
            <p className="text-muted-foreground mb-6">
              Track and manage available beds across different wards and departments.
            </p>
            <div className="grid gap-4">
              <Card>
                <CardHeader>
                  <CardTitle>Live Bed Tracking</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Get real-time updates on available beds and occupancy rates in each department.</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Bed Allocation</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Efficiently manage bed assignments and reservations for incoming patients.</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section
          id="admission"
          className="container mx-auto px-4 md:px-6 grid md:grid-cols-2 gap-8 mt-12">
          <div>
            <h2 className="text-3xl font-bold mb-4">Patient Admission</h2>
            <p className="text-muted-foreground mb-6">
              Streamline the patient admission process and manage medical records.
            </p>
            <div className="grid gap-4">
              <Card>
                <CardHeader>
                  <CardTitle>Online Registration</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Allow patients to easily register and submit their information online.</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Medical Records</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Securely store and manage patient medical history and records.</p>
                </CardContent>
              </Card>
            </div>
          </div>
          <div>
            <img
              src="/placeholder.svg"
              alt="Patient Admission"
              width={600}
              height={400}
              className="rounded-lg object-cover"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
          </div>
        </section>
        <section
          id="integration"
          className="container mx-auto px-4 md:px-6 grid md:grid-cols-2 gap-8 mt-12">
          <div>
            <img
              src="/placeholder.svg"
              alt="City-wide Integration"
              width={600}
              height={400}
              className="rounded-lg object-cover"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
          </div>
          <div>
            <h2 className="text-3xl font-bold mb-4">City-wide Integration</h2>
            <p className="text-muted-foreground mb-6">
              Coordinate with other healthcare facilities in the city for seamless patient care.
            </p>
            <div className="grid gap-4">
              <Card>
                <CardHeader>
                  <CardTitle>Centralized Database</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Maintain a centralized patient database for easy access and coordination.</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Referral and Transfers</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Facilitate patient referrals and transfers between healthcare facilities.</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="bg-primary text-primary-foreground py-6 px-4 md:px-6 flex items-center justify-between">
        <p>&copy; 2024 Hospital Management. All rights reserved.</p>
        <div className="flex gap-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Terms of Service
          </Link>
        </div>
      </footer>
    </div>)
  );
}
